# Generated by Django 5.1.2 on 2024-10-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Volkswagen', 'Volkswagen'), ('BMW', 'BMW'), ('NISSAN', 'NISSAN'), ('Audi', 'Audi'), ('Porsche', 'Porsche'), ('Ford', 'Ford'), ('Nord Motion', 'Nord Motion'), ('Mercedez Benz', 'Mercedez Benz'), ('Toyota', 'Toyota')], max_length=50),
        ),
    ]
