# Generated by Django 5.1.2 on 2024-10-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0002_alter_car_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Cars',
        ),
    ]
