# Generated by Django 5.1.2 on 2024-10-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0005_alter_cars_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='slug',
            new_name='slugs',
        ),
    ]
