# Generated by Django 5.1.2 on 2024-10-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0006_rename_slug_cars_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='slugs',
        ),
    ]
