# Generated by Django 5.1.2 on 2024-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0007_remove_cars_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
