# Generated by Django 5.1.2 on 2024-10-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0013_booking_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='dropoff_datetime',
            new_name='dropoff_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='pickup_datetime',
            new_name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_active',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='Credit Card', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropoff_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(max_length=255),
        ),
    ]
