# Generated by Django 5.1.2 on 2024-10-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0014_rename_dropoff_datetime_booking_dropoff_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='car',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
