# Generated by Django 5.1.2 on 2024-10-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0016_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
