# Generated by Django 5.1.2 on 2024-10-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0017_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drop_location',
            field=models.CharField(default='n/a', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(default='n/a', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
