# Generated by Django 5.1.2 on 2024-10-18 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0018_booking_drop_location_booking_pickup_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_active',
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('number_of_persons', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitepages.cars')),
                ('drop_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_bookings', to='sitepages.location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_bookings', to='sitepages.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddConstraint(
            model_name='carbooking',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_persons__gte', 1)), name='valid_number_of_persons'),
        ),
    ]
