# Generated by Django 5.1.2 on 2024-10-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0021_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(default='unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
        ),
    ]
